extra_srcs = [
    "src/docs/handlers_intro.md",
    "src/docs/error_handling.md",
    "src/docs/extract.md",
    "src/docs/debugging_handler_type_errors.md",
    "src/docs/middleware.md",
    "src/docs/response.md",
    "src/docs/method_routing/fallback.md",
    "src/docs/method_routing/layer.md",
    "src/docs/method_routing/route_layer.md",
    "src/docs/method_routing/merge.md",
    "src/docs/routing/without_v07_checks.md",
    "src/docs/routing/route.md",
    "src/docs/routing/route_service.md",
    "src/docs/routing/nest.md",
    "src/docs/routing/merge.md",
    "src/docs/routing/layer.md",
    "src/docs/routing/route_layer.md",
    "src/docs/routing/fallback.md",
    "src/docs/routing/method_not_allowed_fallback.md",
    "src/docs/routing/with_state.md",
    "src/docs/routing/into_make_service_with_connect_info.md",
]